"""init schema

Revision ID: dacac0583529
Revises: 
Create Date: 2026-03-11 20:03:51.537226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dacac0583529'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dojos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dojos_id'), 'dojos', ['id'], unique=False)
    op.create_index(op.f('ix_dojos_slug'), 'dojos', ['slug'], unique=True)
    op.create_table('turmas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dojo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('day_of_week', sa.String(length=16), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tipo', sa.Enum('regular', 'kids', name='turma_tipo'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turmas_day_of_week'), 'turmas', ['day_of_week'], unique=False)
    op.create_index(op.f('ix_turmas_dojo_id'), 'turmas', ['dojo_id'], unique=False)
    op.create_index(op.f('ix_turmas_id'), 'turmas', ['id'], unique=False)
    op.create_index(op.f('ix_turmas_tipo'), 'turmas', ['tipo'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('dojo_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_dojo_id'), 'users', ['dojo_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dojo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_dojo_id'), 'students', ['dojo_id'], unique=False)
    op.create_index(op.f('ix_students_email'), 'students', ['email'], unique=False)
    op.create_index(op.f('ix_students_id'), 'students', ['id'], unique=False)
    op.create_table('check_ins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dojo_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_in_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['checked_in_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_check_ins_checked_in_by_user_id'), 'check_ins', ['checked_in_by_user_id'], unique=False)
    op.create_index(op.f('ix_check_ins_dojo_id'), 'check_ins', ['dojo_id'], unique=False)
    op.create_index(op.f('ix_check_ins_id'), 'check_ins', ['id'], unique=False)
    op.create_index(op.f('ix_check_ins_occurred_at'), 'check_ins', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_check_ins_student_id'), 'check_ins', ['student_id'], unique=False)
    op.create_index(op.f('ix_check_ins_turma_id'), 'check_ins', ['turma_id'], unique=False)
    op.create_table('student_guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dojo_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_guardians_dojo_id'), 'student_guardians', ['dojo_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_id'), 'student_guardians', ['id'], unique=False)
    op.create_index(op.f('ix_student_guardians_student_id'), 'student_guardians', ['student_id'], unique=False)
    op.create_index(op.f('ix_student_guardians_user_id'), 'student_guardians', ['user_id'], unique=False)
    op.create_table('turma_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turma_enrollments_id'), 'turma_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_turma_enrollments_student_id'), 'turma_enrollments', ['student_id'], unique=False)
    op.create_index(op.f('ix_turma_enrollments_turma_id'), 'turma_enrollments', ['turma_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turma_enrollments_turma_id'), table_name='turma_enrollments')
    op.drop_index(op.f('ix_turma_enrollments_student_id'), table_name='turma_enrollments')
    op.drop_index(op.f('ix_turma_enrollments_id'), table_name='turma_enrollments')
    op.drop_table('turma_enrollments')
    op.drop_index(op.f('ix_student_guardians_user_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_student_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_id'), table_name='student_guardians')
    op.drop_index(op.f('ix_student_guardians_dojo_id'), table_name='student_guardians')
    op.drop_table('student_guardians')
    op.drop_index(op.f('ix_check_ins_turma_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_student_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_occurred_at'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_dojo_id'), table_name='check_ins')
    op.drop_index(op.f('ix_check_ins_checked_in_by_user_id'), table_name='check_ins')
    op.drop_table('check_ins')
    op.drop_index(op.f('ix_students_id'), table_name='students')
    op.drop_index(op.f('ix_students_email'), table_name='students')
    op.drop_index(op.f('ix_students_dojo_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_dojo_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_turmas_tipo'), table_name='turmas')
    op.drop_index(op.f('ix_turmas_id'), table_name='turmas')
    op.drop_index(op.f('ix_turmas_dojo_id'), table_name='turmas')
    op.drop_index(op.f('ix_turmas_day_of_week'), table_name='turmas')
    op.drop_table('turmas')
    op.drop_index(op.f('ix_dojos_slug'), table_name='dojos')
    op.drop_index(op.f('ix_dojos_id'), table_name='dojos')
    op.drop_table('dojos')
    # ### end Alembic commands ###
